export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';
export const LOGIN_LOAD_TOKEN_REQUEST = 'auth/LOGIN_LOAD_TOKEN_REQUEST';
export const LOGIN_LOAD_TOKEN_SUCCESS = 'auth/LOGIN_LOAD_TOKEN_SUCCESS';
export const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
